### ISSUE TITLE
MWE?

### ISSUE THREAD

**Issue by caleblareau** [databio/pararead#14]
Hi,

This looks super useful! I'd love to implement it in some of my work. Do you all have a minimal working example to get started? Maybe something as simple as counting the number of reads on each chromosome with `pararead` compared to a typical `pysam` implementation?

**Comment by vreuter** [comment]
Thanks for reaching out -- glad to hear it may be of some use. Currently, the projects where we've implemented the `ParaReadProcessor` are private, but we will create an example here for reference so that the usage model is more apparent and you can see if you'd like to use it. Having an example like that is a great idea anyhow and is something that will be nice to include.

**Comment by vreuter** [comment]
@caleblareau I've created https://github.com/databio/pararead/pull/15 to provide an example of how to implement and use a `ParaReadProcessor`. Feel free to check it out whenever you'd like to give it a try, and please feel free to provide any feedback or suggestions!

**Comment by vreuter** [comment]
In master as of https://github.com/databio/pararead/pull/18
