### ISSUE TITLE
how to attach a logger 

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#19]
@vreuter I can't figure out how to make a child script that uses a class that extends `ParaReadProcessor` can make sure of the LOGGER functions.

Would you mind updating the example to show how it could use varying logging levels, that are parameterizable with a command-line option?

I have got this far:

```
from pararead.processor import _LOGGER
_LOGGER.info("[Name: " + chrom + "; Size: " + str(chrom_size) + "]") # shows up

_LOGGER.debug("debug message")  # can't figure out how to output this.
```

**Comment by nsheff** [comment]
excellent, that works for me now.

I'm not clear on the difference between the `verbosity` and `loglevel` options -- is it necessary to include both?

**Comment by nsheff** [comment]
I also am not clear on the difference between the `stream` and `logfile` options -- can these be consolidated as well?

**Comment by vreuter** [comment]
`verbosity` and `loglevel` are provided separately to accommodate either perspective that's possible when specifying logging level numerically. A name like `DEBUG` should work with `--loglevel`, but so should an integral value since that's how `logging` internally handles the named levels.
When specifying logging level that way (numerically), though, I think we decided that it's a little more intuitive to have a greater value produce the same or more messages than a lower value. 

This declaration maps verbosity (integral) values to logging levels
```
LEVEL_BY_VERBOSITY = ["ERROR", "WARN", "INFO", "DEBUG"]
```
so that for `--verbosity`, 0 --> `ERROR`, 1 --> `WARN`, etc.

If someone accidentally uses both the `--verbosity` and `--loglevel` style of specification, `--verbosity` is used and `--loglevel` is ignored.

I sort of like having both but am fine with moving to one model or the other.

**Comment by vreuter** [comment]
The `stream` and `logfile` options distinguish between logging to console vs. writing to disk. For `--stream`, `OUT` and `ERR` are the only allowed arguments, while a filepath is used as the argument to `logfile`.

**Comment by vreuter** [comment]
Similar to the level/verbosity, I don't have a strong preference re: messages' destination/target. I kind of like making the distinction obvious at the user level, but am also fine with combining those into a single option, then parsing the argument(s) and acting differently according to the target type implied by the argument.

**Comment by nsheff** [comment]
I think we should simplify by folding `--loglevel` into `--verbosity` (they do the same thing).

I think `stream` should be modifiable by the subclass developer, but there's no reason to make that command-line modifiable by default. I would default it to `ERR` and then make that an option that can be passed to the processor parent class or something, but remove it from the auto parameter add.

for a particular tool the developer could add that if they wanted.

**Comment by vreuter** [comment]
OK, totally agree re: the `--stream` option.

Combining the level/verbosity is probably still the way to go, but there is one downside that occurred to me. First, if they are combined, the level names, e.g. `INFO` still be usable? The (admittedly minor) loss that seems unavoidable is playing nicely with packages that emit messages at custom levels.

For example, in `looper`, there's a [custom logging level definition](https://github.com/pepkit/looper/blob/master/looper/__init__.py#L56). I'm fine with foregoing some ease of use of that sort of functionality and forcing developers to do some custom CLI work to hook into it, but I wanted to point it out as a minor cost.

**Comment by nsheff** [comment]
along these lines I'll raise a 3rd point:

I think we can eliminate `--logfile` as well; the unix stderr pipes accomplishes this, there's no reason for us to reimplement it (every single program could offer such a parameter, but it would be unnecessary).

in this case, this logfile is identical to stderr, so it's an unnecessary argument in the general case. 

like the `stream` one, a developer could add that in if they needed it for a particular tool, but it's not a generally useful option that warrants sticking in the always category

**Comment by vreuter** [comment]
So...
- [ ] Remove `--logfile` and `--stream`, relying on default stream handler that we provide and use these options only if they're added by a developer
- [ ] Remove `--loglevel`, favoring just `--verbosity`
- [ ] Allow `--verbosity` argument to be a level name, while still interpreting integral values as they are now, as relative levels that we implicitly map into `logging` levels, so that we have the "higher level --> more messages" logic
?

**Comment by vreuter** [comment]
Do you agree with the above? Also, in `setup_logger`, `TRACE` is added with a numerical value of 5. Should that also be removed?

**Comment by vreuter** [comment]
Actually, just feel free to reply by editing [this issue](https://github.com/databio/pararead/issues/22)

**Comment by vreuter** [comment]
Closing for now in favor of https://github.com/databio/pararead/issues/22
